version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"  # 3.8 is EOL; 3.10+ is recommended for stability & newer packages

sphinx:
  configuration: source/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt
