'''
========================================================================
        ╦ ╦┌─┐┌─┐┌─┐┌─┐┌┬┐  ╔╦╗┌─┐┌─┐┌┬┐┬ ┬  ╔╗ ┌─┐┬  ┌─┐┬ ┬┌─┐
        ╠═╣│ │└─┐└─┐├─┤│││  ║║║├─┤│ ┬ ││└┬┘  ╠╩╗├─┤│  ├─┤├─┤├─┤
        ╩ ╩└─┘└─┘└─┘┴ ┴┴ ┴  ╩ ╩┴ ┴└─┘─┴┘ ┴   ╚═╝┴ ┴┴─┘┴ ┴┴ ┴┴ ┴
========================================================================
# Author: Hossam Magdy Balaha
# Initial Creation Date: Aug 2nd, 2025
# Last Modification Date: Aug 2nd, 2025
# Permissions and Citation: Refer to the README file.
'''

import torch, re, nltk, textstat, sys
import numpy as np
import torch.nn as nn
from rouge import Rouge
from collections import Counter
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.translate.chrf_score import sentence_chrf
from sklearn.metrics import accuracy_score, f1_score

# Increase recursion limit to handle deep recursive calls in some metrics.
sys.setrecursionlimit(10 ** 6)


# Download necessary NLTK resources for tokenization and POS tagging.
# nltk.download("punkt_tab")
# nltk.download("averaged_perceptron_tagger_eng")


class TextGenerationMetrics(object):
  def __init__(self, tokenizer=None):
    self.tokenizer = tokenizer  # If provided, will be used for tokenization.
    self.rouge = Rouge()  # Initialize ROUGE metric.
    self.smoothing = SmoothingFunction().method1  # Smoothing function for BLEU score.

  def CalculateBLEU(
    self,
    generatedText,  # Generated text to evaluate.
    referenceText,  # Reference text to compare against.
    # Weights for n-gram precision (default is uniform for 1-4 grams).
    weights=(0.25, 0.25, 0.25, 0.25),
  ):
    '''
    Calculate BLEU score for generated text against reference text.
    This function tokenizes the input texts and computes the BLEU score using
    NLTK's sentence_bleu function with specified n-gram weights and smoothing.
    This is useful for evaluating the quality of generated text in natural language processing tasks.
    Parameters:
      generatedText (str): The text generated by the model.
      referenceText (str): The reference text to compare against.
      weights (tuple): Weights for n-gram precision (default is uniform for 1-4 grams).
    Returns:
      float: The BLEU score for the generated text against the reference text.
    '''

    # Tokenize texts.
    generatedTokens = generatedText.split()
    referenceTokens = referenceText.split()

    # Calculate BLEU score with smoothing.
    bleuScore = sentence_bleu(
      [referenceTokens],  # Reference tokens as a list of lists.
      generatedTokens,  # Generated tokens.
      weights=weights,  # Weights for n-gram precision.
      smoothing_function=self.smoothing,  # Smoothing function to handle zero counts.
    )
    return bleuScore

  def CalculateROUGE(self, generatedText, referenceText):
    '''
    Calculate ROUGE scores for generated text against reference text.
    This function computes ROUGE-1, ROUGE-2, and ROUGE-L scores using the Rouge library.
    Parameters:
      generatedText (str): The text generated by the model.
      referenceText (str): The reference text to compare against.
    Returns:
      dict: A dictionary containing ROUGE-1, ROUGE-2, and ROUGE-L scores.
    '''

    def _CleanTextForRouge(text):
      # Remove extra whitespace and ensure minimum length.
      cleaned = re.sub(r"\s+", " ", text.strip())
      return cleaned if (len(cleaned) > 0) else " "

    # Clean texts for ROUGE calculation.
    cleanedGenText = _CleanTextForRouge(generatedText)
    cleanedRefText = _CleanTextForRouge(referenceText)

    # Calculate ROUGE scores.
    scores = self.rouge.get_scores(cleanedGenText, cleanedRefText)[0]

    return {
      "rouge-1": scores["rouge-1"]["f"],
      "rouge-2": scores["rouge-2"]["f"],
      "rouge-l": scores["rouge-l"]["f"]
    }

  def CalculateMETEOR(self, generatedText, referenceText):
    '''
    Calculate METEOR score for generated text against reference text.
    This function computes the METEOR score using a simple approximation based on precision, recall, and F1 score.
    Parameters:
      generatedText (str): The text generated by the model.
      referenceText (str): The reference text to compare against.
    Returns:
      float: The METEOR score for the generated text against the reference text.
    '''

    def _ApproximateMETEOR(genText, refText):
      genWords = set(genText.lower().split())
      refWords = set(refText.lower().split())

      if (len(genWords) == 0 and len(refWords) == 0):
        return 1.0
      if (len(genWords) == 0 or len(refWords) == 0):
        return 0.0

      intersection = genWords.intersection(refWords)
      precision = len(intersection) / len(genWords)
      recall = len(intersection) / len(refWords)

      if (precision + recall == 0):
        return 0.0

      f1 = 2.0 * (precision * recall) / (precision + recall)
      return f1

    return _ApproximateMETEOR(generatedText, referenceText)

  def CalculateEditDistance(self, generatedText, referenceText):
    '''
    Calculate edit distance similarity between generated and reference text.
    This function computes the edit distance (Levenshtein distance) between two texts
    and normalizes it to return a similarity score.
    This is useful for evaluating how similar two pieces of text are in terms of their content.
    Parameters:
      generatedText (str): The text generated by the model.
      referenceText (str): The reference text to compare against.
    Returns:
      float: The similarity score based on edit distance (1.0 means identical, 0.0 means completely different).
    '''

    genTokens = generatedText.split()
    refTokens = referenceText.split()

    # Dynamic programming for edit distance.
    m, n = len(genTokens), len(refTokens)
    dp = [[0] * (n + 1) for _ in range(m + 1)]

    # Initialize base cases.
    for i in range(m + 1):
      dp[i][0] = i
    for j in range(n + 1):
      dp[0][j] = j

    # Fill DP table.
    for i in range(1, m + 1):
      for j in range(1, n + 1):
        if (genTokens[i - 1] == refTokens[j - 1]):
          dp[i][j] = dp[i - 1][j - 1]
        else:
          dp[i][j] = 1 + min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1])

    # Normalize by maximum length
    maxLen = max(m, n)
    if (maxLen == 0):
      return 1.0

    normalizedDistance = dp[m][n] / maxLen
    # Return similarity instead of distance.
    return 1.0 - normalizedDistance

  def CalculateSemanticSimilarity(self, generatedText, referenceText):
    '''
    Calculate semantic similarity between generated and reference text.
    This function computes the Jaccard similarity based on word overlap between two texts.
    This is a simple approximation of semantic similarity, useful for evaluating how similar two pieces of text
    are in terms of their content.
    Parameters:
      generatedText (str): The text generated by the model.
      referenceText (str): The reference text to compare against.
    Returns:
      float: The Jaccard similarity score (1.0 means identical, 0.0 means completely different).
    '''

    # Simple word overlap approach as approximation.
    genWords = set(generatedText.lower().split())
    refWords = set(referenceText.lower().split())

    if (len(genWords) == 0 and len(refWords) == 0):
      return 1.0
    if (len(genWords) == 0 or len(refWords) == 0):
      return 0.0

    # Jaccard similarity.
    intersection = len(genWords.intersection(refWords))
    union = len(genWords.union(refWords))
    jaccard = intersection / union if (union > 0) else 0.0

    return jaccard

  def CalculateLengthRatio(self, generatedText, referenceText):
    genLen = len(generatedText.split())
    refLen = len(referenceText.split())

    if refLen == 0:
      return 0.0 if genLen == 0 else float("inf")

    return genLen / refLen

  def CalculatePerplexity(self, generatedTokens, referenceTokens):
    '''
    Calculate the perplexity of generated tokens against reference tokens.
    This function computes the perplexity score, which is a measure of how well
    the generated text predicts the reference text.
    Perplexity = exp(- (1/N) * sum(log(P(token))))
    For identical texts: perplexity = 1.0
    Parameters:
      generatedTokens (list): List of tokens generated by the model.
      referenceTokens (list): List of tokens in the reference text.
    Returns:
      float: The perplexity score for the generated tokens against the reference tokens.
        If the reference and generated tokens are identical, then the perplexity is 1.0.
    '''

    if (len(referenceTokens) == 0):
      return float("inf")  # Avoid division by zero.

    # Count occurrences of each token in the reference text.
    refCounter = Counter(referenceTokens)
    totalRefTokens = len(referenceTokens)

    # Calculate probabilities for each generated token.
    logProbs = []
    for token in generatedTokens:
      # Probability of token in reference text.
      prob = refCounter[token] / totalRefTokens if (token in refCounter) else 1e-10
      # Avoid log(0) which would be -inf.
      if (prob > 0):
        logProbs.append(np.log(prob))
      else:
        # If probability is 0 or invalid, return high perplexity.
        return float("inf")

    # Handle case where we have no valid probabilities.
    if (len(logProbs) == 0):
      return float("inf")

    # Calculate perplexity: exp(-mean(log probabilities)).
    avgLogProb = np.mean(logProbs)
    perplexity = np.exp(-avgLogProb)

    # Normalize by number of generated tokens.
    perplexity = perplexity / len(generatedTokens)

    return perplexity

  def CalculateAccuracy(self, generatedText, referenceText):
    '''
    Calculate accuracy of generated text against reference text.
    This function computes the accuracy score based on exact matches between
    generated and reference texts.
    Parameters:
      generatedText (str): The text generated by the model.
      referenceText (str): The reference text to compare against.
    Returns:
      float: The accuracy score (1.0 means perfect match, 0.0 means no match).
    '''

    genTokens = generatedText.split()
    refTokens = referenceText.split()

    # Calculate accuracy as the proportion of matching tokens.
    if len(refTokens) == 0:
      return 1.0 if len(genTokens) == 0 else 0.0

    correct = sum(1 for g, r in zip(genTokens, refTokens) if g == r)
    accuracy = correct / len(refTokens)

    return accuracy

  def CalculateF1Score(self, generatedText, referenceText):
    '''
    Calculate F1 score of generated text against reference text.
    This function computes the F1 score based on precision and recall of matching tokens.
    Parameters:
      generatedText (str): The text generated by the model.
      referenceText (str): The reference text to compare against.
    Returns:
      float: The F1 score (1.0 means perfect match, 0.0 means no match).
    '''

    genTokens = generatedText.split()
    refTokens = referenceText.split()

    if len(genTokens) == 0 or len(refTokens) == 0:
      return 0.0

    # Count matches.
    matches = sum(1 for g in genTokens if g in refTokens)

    precision = matches / len(genTokens)
    recall = matches / len(refTokens)

    if (precision + recall) == 0:
      return 0.0

    f1 = 2.0 * (precision * recall) / (precision + recall)

    return f1

  def CalculateCHRF(self, generatedText, referenceText):
    '''
    Calculate CHRF score for generated text against reference text.
    This function computes the character n-gram F-score, which is useful for evaluating
    the quality of generated text in natural language processing tasks.
    Parameters:
      generatedText (str): The text generated by the model.
      referenceText (str): The reference text to compare against.
    Returns:
      float: The CHRF score for the generated text against the reference text.
    '''

    chrfScore = sentence_chrf(generatedText, referenceText)
    return chrfScore

  def CalculateRepetitionRate(self, generatedText, n=3):
    '''
    Calculate the repetition rate of n-grams in the generated text.
    This function computes the proportion of n-grams that are repeated in the generated text.
    A higher repetition rate indicates more redundancy in the generated text.
    This is useful for evaluating the diversity and originality of generated text in
    natural language processing tasks.
    Parameters:
      generatedText (str): The text generated by the model.
      n (int): The size of the n-grams to consider (default is 3).
    Returns:
      float: The repetition rate of n-grams in the generated text
        (0.0 means no repetition, 1.0 means all n-grams are repeated).
    '''

    tokens = generatedText.split()
    if (len(tokens) < n):
      return 0.0

    ngrams = [
      tuple(tokens[i:i + n])
      for i in range(len(tokens) - n + 1)
    ]
    uniqueNgrams = set(ngrams)

    if (len(ngrams) == 0):
      return 0.0

    repetitionRate = 1.0 - (len(uniqueNgrams) / len(ngrams))
    return repetitionRate

  def CalculateLexicalDiversity(self, generatedText):
    '''
    Calculate lexical diversity of the generated text.
    Lexical diversity is the ratio of unique words to total words in the text.
    A higher lexical diversity indicates a richer vocabulary and less repetition.
    This is useful for evaluating the richness and variety of vocabulary in generated text.
    Parameters:
      generatedText (str): The text generated by the model.
    Returns:
      float: The lexical diversity score (0.0 means no diversity, 1.0 means maximum diversity).
    '''

    tokens = generatedText.lower().split()
    if (len(tokens) == 0):
      return 0.0

    uniqueTokens = set(tokens)
    return len(uniqueTokens) / len(tokens)

  def CalculateReadabilityScore(self, generatedText):
    '''
    Calculate the Flesch-Kincaid grade level of the generated text.
    This function computes the readability score based on the Flesch-Kincaid formula,
    which estimates the grade level required to understand the text.
    A lower score indicates easier readability, while a higher score indicates more complex text.
    This is useful for evaluating the readability of generated text in natural language processing tasks.
    Parameters:
      generatedText (str): The text generated by the model.
    Returns:
      float: The Flesch-Kincaid grade level score for the generated text.
        Lower scores indicate easier readability, while higher scores indicate more complex text.
    '''

    return textstat.flesch_kincaid_grade(generatedText)

  def CalculateInformationDensity(self, generatedText):
    '''
    Calculate information density of the generated text.
    Information density is the ratio of content words (nouns, verbs, adjectives, adverbs
    ) to total words in the text.
    A higher information density indicates more informative content.
    This is useful for evaluating the informativeness of generated text in natural language processing tasks.
    Parameters:
      generatedText (str): The text generated by the model.
    Returns:
      float: The information density score (0.0 means no content words, 1.0 means all words are content words).
    '''

    tokens = nltk.word_tokenize(generatedText.lower())
    posTags = nltk.pos_tag(tokens)

    # Content words: nouns, verbs, adjectives, adverbs.
    contentWords = [
      word for word, pos in posTags
      if (pos.startswith(('NN', 'VB', 'JJ', 'RB')))
    ]

    if (len(tokens) == 0):
      return 0.0

    return len(contentWords) / len(tokens)

  def CalculateHallucinationRate(self, generatedText, referenceText):
    '''
    Calculate hallucination rate of generated text against reference text.
    This function computes the proportion of words in the generated text that do not appear in the reference
    text. A higher hallucination rate indicates more divergence from the reference text.
    This is useful for evaluating the factual accuracy of generated text in natural language processing tasks.
    Parameters:
      generatedText (str): The text generated by the model.
      referenceText (str): The reference text to compare against.
    Returns:
      float: The hallucination rate for the generated text against the reference text.
        A value between 0.0 and 1.0, where 0.0 means no hallucination and 1.0 means all words are hallucinated.
    '''

    genWords = set(generatedText.lower().split())
    refWords = set(referenceText.lower().split())

    if (len(genWords) == 0):
      return 0.0

    hallucinatedWords = genWords - refWords
    return len(hallucinatedWords) / len(genWords)

  def CalculateOmissionRate(self, generatedText, referenceText):
    genWords = set(generatedText.lower().split())
    refWords = set(referenceText.lower().split())

    if (len(refWords) == 0):
      return 0.0

    omittedWords = refWords - genWords
    return len(omittedWords) / len(refWords)

  def CalculateFactualityScore(self, generatedText, referenceText):
    '''
    Calculate factuality score based on hallucination and omission rates.
    This function combines hallucination and omission rates to compute a factuality score.
    Higher is better.
    This is useful for evaluating the factual accuracy of generated text in natural language processing tasks.
    Parameters:
      generatedText (str): The text generated by the model.
      referenceText (str): The reference text to compare against.
    Returns:
      float: The factuality score for the generated text against the reference text.
        A value between 0.0 and 1.0, where 1.0 means perfect factuality (no hallucinations or omissions).
    '''

    hallucinationRate = self.CalculateHallucinationRate(generatedText, referenceText)
    omissionRate = self.CalculateOmissionRate(generatedText, referenceText)

    precision = 1.0 - hallucinationRate  # Lower hallucination = higher precision.
    recall = 1.0 - omissionRate  # Lower omission = higher recall.

    if (precision + recall == 0):
      return 0.0

    f1 = 2.0 * (precision * recall) / (precision + recall)
    return f1

  def CalculateAllMetrics(self, generatedText, referenceText):
    '''
    Calculate all metrics for generated text against reference text.
    This function computes BLEU, ROUGE, METEOR, edit distance similarity, semantic similarity,
    length ratio, perplexity, accuracy, F1 score, CHRF score, repetition rate,
    lexical diversity, readability score, information density, hallucination rate,
    omission rate, and factuality score.
    Parameters:
      generatedText (str): The text generated by the model.
      referenceText (str): The reference text to compare against.
    Returns:
      dict: A dictionary containing all computed metrics.
    '''

    return {
      "BLEU"              : self.CalculateBLEU(generatedText, referenceText),
      "ROUGE"             : self.CalculateROUGE(generatedText, referenceText),
      "METEOR"            : self.CalculateMETEOR(generatedText, referenceText),
      "EditDistance"      : self.CalculateEditDistance(generatedText, referenceText),
      "SemanticSimilarity": self.CalculateSemanticSimilarity(generatedText, referenceText),
      "LengthRatio"       : self.CalculateLengthRatio(generatedText, referenceText),
      "Perplexity"        : self.CalculatePerplexity(generatedText.split(), referenceText.split()),
      "Accuracy"          : self.CalculateAccuracy(generatedText, referenceText),
      "F1Score"           : self.CalculateF1Score(generatedText, referenceText),
      "CHRF"              : self.CalculateCHRF(generatedText, referenceText),
      "RepetitionRate"    : self.CalculateRepetitionRate(generatedText),
      "LexicalDiversity"  : self.CalculateLexicalDiversity(generatedText),
      "ReadabilityScore"  : self.CalculateReadabilityScore(generatedText),
      "InformationDensity": self.CalculateInformationDensity(generatedText),
      "HallucinationRate" : self.CalculateHallucinationRate(generatedText, referenceText),
      "OmissionRate"      : self.CalculateOmissionRate(generatedText, referenceText),
      "FactualityScore"   : self.CalculateFactualityScore(generatedText, referenceText),
    }


if __name__ == "__main__":
  # Initialize metrics calculator.
  metrics = TextGenerationMetrics()

  results = [
    ("Invasive ductal carcinoma grade 2", "Invasive ductal carcinoma grade 2"),
    ("Invasive ductal carcinoma grade 2", "Invasive ductal carcinoma grade 3"),
    ("The quick brown fox jumps over the lazy dog.", "The quick brown fox jumps over the lazy dog."),
  ]

  for genText, refText in results:
    bleuScore = metrics.CalculateBLEU(genText, refText)
    rougeScores = metrics.CalculateROUGE(genText, refText)
    meteorScore = metrics.CalculateMETEOR(genText, refText)
    editDistance = metrics.CalculateEditDistance(genText, refText)
    semanticSimilarity = metrics.CalculateSemanticSimilarity(genText, refText)
    lengthRatio = metrics.CalculateLengthRatio(genText, refText)
    perplexity = metrics.CalculatePerplexity(genText.split(), refText.split())
    accuracy = metrics.CalculateAccuracy(genText, refText)
    f1Score = metrics.CalculateF1Score(genText, refText)
    chrfScore = metrics.CalculateCHRF(genText, refText)
    repetitionRate = metrics.CalculateRepetitionRate(genText)
    lexicalDiversity = metrics.CalculateLexicalDiversity(genText)
    readabilityScore = metrics.CalculateReadabilityScore(genText)
    informationDensity = metrics.CalculateInformationDensity(genText)
    hallucinationRate = metrics.CalculateHallucinationRate(genText, refText)
    omissionRate = metrics.CalculateOmissionRate(genText, refText)
    factualityScore = metrics.CalculateFactualityScore(genText, refText)

    print(f"BLEU Score: {bleuScore:.4f}")
    print(
      f"ROUGE-1: {rougeScores['rouge-1']:.4f}, ROUGE-2: {rougeScores['rouge-2']:.4f}, "
      f"ROUGE-L: {rougeScores['rouge-l']:.4f}"
    )
    print(f"METEOR Score: {meteorScore:.4f}")
    print(f"Edit Distance Similarity: {editDistance:.4f}")
    print(f"Semantic Similarity: {semanticSimilarity:.4f}")
    print(f"Length Ratio: {lengthRatio:.4f}")
    print(f"Perplexity: {perplexity:.4f}")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"F1 Score: {f1Score:.4f}")
    print(f"CHRF Score: {chrfScore:.4f}")
    print(f"Repetition Rate: {repetitionRate:.4f}")
    print(f"Lexical Diversity: {lexicalDiversity:.4f}")
    print(f"Readability Score: {readabilityScore:.4f}")
    print(f"Information Density: {informationDensity:.4f}")
    print(f"Hallucination Rate: {hallucinationRate:.4f}")
    print(f"Omission Rate: {omissionRate:.4f}")
    print(f"Factuality Score: {factualityScore:.4f}")
    print("=" * 80)
